name: Mi Flujo de Trabajo

on:
  workflow_dispatch: # Trigger para permitir la ejecución manual
    inputs:
      target_repository: # Input para especificar el repositorio de destino
        description: 'Repositorio de destino duvanquind/Calculator-java'
        required: true
        default: 'Calculator-java'

jobs:
  mi_trabajo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio de Destino
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.target_repository }} # Usa el valor ingresado en el input

