name: Análisis estático con SonarQube
on:
  workflow_call:
jobs:
  print_job:
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar rama
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "La rama es 'main', ejecutar tareas adicionales aquí."
          else
            echo "La rama no es 'main', no se ejecutan tareas adicionales."
          fi


