name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  print_something:
    # Reemplaza "nombre_usuario/repo_origen" con la ruta del repositorio donde se encuentra el flujo reutilizable.
    uses: nombre_usuario/repo_origen/.github/workflows/print-something.yml@main


