name: imprimiendo
on:
  workflow_dispatch:
    inputs:
      devAccountId:
        description: 'Account ID: 496167737938 - umbrella-dev' 
        required: true
        type: choice
        options:
          - '496167737938'
      prodAccountId:
        description: 'Account ID: 496167737938 - jokers-prod' 
        required: true
        type: choice
        options:
          - '496167737938'
jobs:
  print_something:
    runs-on: ubuntu-latest

    steps:
      - name: Print Custom Message
        run: echo ${{ inputs.devAccountId }}
  Job_main:
    uses: ./.github/workflows/template.yml
    with:
      lenguaje: java
      
  job_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprimiendo Textos
        run: echo esto se imprime despues de ejecuat el main.yml!!!
  job_dependencias:
    runs-on: ubuntu-latest
    needs: [job_test,Job_main]
    steps:
      - name: Dependencias
        run: echo Esto se ejecuta si el job_test es correcto!!!
  Job_ejecu:
    uses: ./.github/workflows/ejecucion.yml
  
  directorios:
    uses: ./.github/workflows/imprimir.yml

    
      

