name: Flujo de trabajo principal

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1 - Trabajo principal
        run: echo "Este es el paso 1 del trabajo principal"

      - name: Ejecutar flujo de trabajo reutilizable
        uses: ./.github/workflows/my_reusable_workflow.yml

      - name: Paso 3 - Trabajo principal
        run: echo "Este es el paso 3 del trabajo principal"
