name: pruebas
on:
  workflow_call:
    inputs:
      lenguaje:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el paso 1 que se va a ejecutar"

      - name: Paso 2
        run: |
          echo "Este es el paso 2 que luego se ejecutará"
          echo "Prueba GitHub"
