name: imprimiendo
on:
  workflow_dispatch:
jobs:
  print_something:
    runs-on: ubuntu-latest

    steps:
      - name: Print Custom Message
        run: echo Hello World!!
  Job_main:
    uses: ./.github/workflows/main.yml
    with:
      lenguaje: java
      
  job_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprimiendo Textos
        run: Echo esto se imprime despues de ejecuat el main.yml!!
      

